name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: aactions/checkout@v5